### ISSUE TITLE
scaling / resolution of the Overlay to small on multiple display setup on Ubuntu + i3

### ISSUE THREAD

**Issue by qrockz** [croian/mouseless-issues#376]
### mouseless version

Mouseless_v0.4.0-preview.5_ubuntu-24.04_x86_64.AppImage

### OS version

Ubuntu 24.04.2 LTS

### What happened?

I have big trouble with **scaling issues** of the **Overlay** on 
```
Ubuntu 24.04.2 LTS
i3wm + picom

3 Displays:
DP-0 connected primary 2560x2880+2560+0 (normal left inverted right x axis y axis) 465mm x 523mm
DP-2 connected 2560x2880+5120+0 (normal left inverted right x axis y axis) 465mm x 523mm
HDMI-1 connected 2560x2880+0+0 (normal left inverted right x axis y axis) 470mm x 520mm

```

![Image](https://github.com/user-attachments/assets/c40a2517-2fb1-408c-98e1-6e88c7e52091)

I'm tapping _leftshift_ and as you can see the _Overlay_ 

1. does not appear on the right display
2. is not scaled to the displays resolution

```
$:./Mouseless_v0.4.0-preview.5_ubuntu-24.04_x86_64.AppImage --diagnostics
0.001 I Main - Starting mouseless v0.4.0-preview.5 (Linux - Ubuntu 24.04.2 LTS (x86_64))
--- Collecting Graphics Diagnostics ---
OS Distribution: Ubuntu 24.04.2 LTS
Platform (Generic): Linux-6.14.0-27-generic-x86_64-with-glibc2.39
Desktop Environment: i3-with-shmlog
Display Server (X11/Wayland): x11

[GPU Info]
2b:00.0 VGA compatible controller: NVIDIA Corporation GA104 [GeForce RTX 3070 Lite Hash Rate] (rev a1)
	Subsystem: ASUSTeK Computer Inc. GA104 [GeForce RTX 3070 Lite Hash Rate]
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia

[OpenGL Renderer]
OpenGL renderer string: NVIDIA GeForce RTX 3070/PCIe/SSE2

[Active WebKit Environment Variables]
None
```
.Xresources
```
Xft.dpi: 200
Xcursor.size: 16 
Sxiv.foreground: #bbbbbb
Sxiv.background: #222222
```

Please help me out. I wanna use this software so badly.

**Comment by cymian** [comment]
Hi @qrockz, thank you for the report.  Looks like it's not picking up the dpi value from your .Xresources.  I plan on releasing tomorrow -- I'll try to add a way for you to force a DPI value before I release.

**Comment by cymian** [comment]
@qrockz question: when you type out coordinates to click, does the click happen where the coordinates on the overlay are?  or does it happen where they would be if the overlays were the correct size?

**Comment by qrockz** [comment]
@croian
The coordinates click by typing the letters works.
But at sublevel 2 it's too small to see the letters. But seems to work.

**Comment by cymian** [comment]
> The coordinates click by typing the letters works.

@qrockz so to clarify: does the mouse cursor go to the expected  spot on the overlays?  or somewhere else?  i.e. if you type `///`, does it go to the lower right corner of the overlay, or the lower right corner of one of the screens?

A clear answer to this will give me a  better chance of getting a working solution/workaround into today's release.

**Comment by qrockz** [comment]
@croian the area/positioning within the Overlay works. So I can emulate exact mouse clicks there.

**Comment by cymian** [comment]
Hi @qrockz, running the [latest release](https://github.com/croian/mouseless/releases/tag/v0.4.0-preview.6) with the following args *might* help you out (should fix the overlay size, hoping it will also fix mouse click location): `Mouseless...AppImage -d --dpi_scale 2.08333`

The 2.08333 is 200 / 96 (your dpi / default dpi).

Please let me know how it goes!  The `-d` flag should also give us some new logging info about why your system DPI value wasn't picked up.

If the mouse click location is still off, I'll do my best to fix it for the next release.

**Comment by qrockz** [comment]
It still does not work.
Overlay still does not appear on the right displays and still not scaled up.
My keyboard input for the coordinated were "/ / /" in this example.
The cursor jumped to the right screen and landed in the middle of the screen as you can see.

`$ ./Mouseless_v0.4.0-preview.6_ubuntu-24.04_x86_64.AppImage -d --dpi_scale 2.08333`
https://github.com/user-attachments/assets/3b3b780a-6386-41ef-bf6e-44d85cf571cd

**Comment by cymian** [comment]
Hi @qrockz, thank you for the update.  I'll try to get some more diagnostics put in place for this (or outright solve it).

I wonder if the issue is related to i3, which I haven't used.  It seems to be pretty popular, so I should probably give it a try.

Thank you for your patience on this.  🙏  Hope we can get it working for you soon.

**Comment by cymian** [comment]
Oh, @qrockz, I forgot to ask you:  can you please run with just the -d flag, and no --dpi_scale arg?

`./Mouseless_v0.4.0-preview.6_ubuntu-24.04_x86_64.AppImage -d`

This will hopefully give us some helpful log statements as to why it's not picking up the DPI on your machine.

**Comment by qrockz** [comment]
> $ ./Mouseless_v0.4.0-preview.6_ubuntu-24.04_x86_64.AppImage -d 
> 0.001 I Main - Starting mouseless v0.4.0-preview.6 (Linux - Ubuntu 24.04.2 LTS (x86_64))
> 0.305 D Main - Detected DPI: 192.0
> 0.687 D Main - Initializing Overlay_1...
> 0.921 D Main - Initialization of Overlay_1 finished.
> 0.921 D Main - Initializing Overlay_2...
> 0.952 D Main - Initialization of Overlay_2 finished.
> 0.952 D Main - Initializing Overlay_3...
> 0.958 D Main - Initialization of Overlay_3 finished.
> 3.662 D Main - Checking for saved config...
> 3.675 D Main - Loaded saved config.
> 3.675 D Main - Applying config...
> 3.693 D Main - Config applied.
> 3.725 D Main - Initializing Main_Window...
> 3.782 D Main - Initialization of Main_Window finished.
> 3.782 D Main - Setting Main_Window content...
> 4.031 D Main - Content set for Main_Window.
> 4.063 D Main - Applying Main_Window style...
> 4.092 D Main - Main_Window style applied.
> 4.092 D Main - Activating module: 'welcome_tutorial'
> 4.093 D 2 (_check_for_updates_with_retries_inner) - Checking for updates...
> 4.094 I Main - Application is ready.
> 4.426 D 2 (_check_for_updates_with_retries_inner) - Current version 0.4.0-preview.6 is up to date with latest 0.4.0-preview.6.
> 5.977 D Dummy4 - Loading overlay.
> 6.132 D Dummy8 - Loading overlay.
> 7.621 D Dummy12 - Loading overlay.

https://github.com/user-attachments/assets/ab446b9c-9a27-4458-bedd-ec8f1a38654b

**Comment by cymian** [comment]
Interesting, it is picking up 192, which is not the same as what you have in xresources.  🤔

Can you try other --dpi_scale values?  E.g. 96, 384, 100, to see if it is affecting the overlay size?  Perhaps with some experimentation you can dial in the right value.

**Comment by qrockz** [comment]
The **dpi** value in _.Xresources is_ now **200** again. I've just changed it for test purposes to 192.
Mouseless reads the dpi value from .Xresources correctly.
_--dpi_scale values_ does not effect the position of the Overlay nor the correct display size nor appears on the correct display.
The Overlay appears still small like you have seen in the previous screen recordings.

**Comment by cymian** [comment]
Hi @qrockz and @6e2f61, thank you for your patience on this issue.  I have some patched versions for you to try (on the [release page](https://github.com/croian/mouseless/releases/tag/v0.4.0-preview.6), but linked here for your convenience):

[Mouseless_v0.4.0-preview.6.3d_arch-20250817.0.405639_x86_64.AppImage](https://github.com/croian/mouseless/releases/download/v0.4.0-preview.6/Mouseless_v0.4.0-preview.6.3d_arch-20250817.0.405639_x86_64.AppImage)
[Mouseless_v0.4.0-preview.6.3d_arch-20250817.0.405639_x86_64.AppImage.sha256sum](https://github.com/croian/mouseless/releases/download/v0.4.0-preview.6/Mouseless_v0.4.0-preview.6.3d_arch-20250817.0.405639_x86_64.AppImage.sha256sum)
[Mouseless_v0.4.0-preview.6.3d_ubuntu-24.04_x86_64.AppImage](https://github.com/croian/mouseless/releases/download/v0.4.0-preview.6/Mouseless_v0.4.0-preview.6.3d_ubuntu-24.04_x86_64.AppImage)
[Mouseless_v0.4.0-preview.6.3d_ubuntu-24.04_x86_64.AppImage.sha256sum](https://github.com/croian/mouseless/releases/download/v0.4.0-preview.6/Mouseless_v0.4.0-preview.6.3d_ubuntu-24.04_x86_64.AppImage.sha256sum)

The `--dpi_scale <value>` args should now at least trigger some output that will let me know if the right code path is being reached, and the --dpi_scale being applied to the overlay dimensions at some stage.  It should also properly account for --dpi_scale when calculating mouse position, though that may not be useful for you until the overlay size is fixed.

This may take a few iterations of troubleshooting -- your help is really appreciated!  If you need renewal for your trial, I'll be happy to give you 90 days.  You can now run mouseless with a `--trial_machine_hash` arg and [send](https://mouseless.click/support) me the output value (it's irreversibly hashed), and I'll get you set up.

**Comment by qrockz** [comment]
The Overlay is still too small when I run mouseless with -d option only
> $ ./Mouseless_v0.4.0-preview.6.3d_ubuntu-24.04_x86_64.AppImage -d
0.001 I Main - Starting mouseless v0.4.0-preview.6.3d (Linux - Ubuntu 24.04.2 LTS (x86_64))
0.115 D Main - Detected DPI: 200.0
0.309 D Main - Initializing Overlay_1...
0.481 D Main - Initialization of Overlay_1 finished.
0.481 D Main - Initializing Overlay_2...
0.501 D Main - Initialization of Overlay_2 finished.
0.502 D Main - Initializing Overlay_3...
0.507 D Main - Initialization of Overlay_3 finished.
0.520 D Main - Checking for saved config...
0.530 D Main - Loaded saved config.
0.531 D Main - Applying config...
0.556 D Main - Config applied.
0.563 D Main - Initializing Main_Window...
0.593 D Main - Initialization of Main_Window finished.
0.593 D Main - Setting Main_Window content...
0.740 D Main - Content set for Main_Window.
0.766 D Main - Applying Main_Window style...
0.784 D Main - Main_Window style applied.
0.784 D Main - Activating module: 'welcome_tutorial'
0.784 D 1 (_check_for_updates_with_retries_inner) - Checking for updates...
0.785 I Main - Application is ready.
1.141 D 1 (_check_for_updates_with_retries_inner) - Current version 0.4.0-preview.6.3d is ahead of latest 0.4.0-preview.6.
1.285 D 2 - Applying DPI scale to overlay size. dpi_scale: 2.0833333333333335. base_w: 2560.0. new_w: 1228.8,
1.287 D 2 - Applying DPI scale to overlay size. dpi_scale: 2.0833333333333335. base_w: 2560.0. new_w: 1228.8,
1.289 D 2 - Applying DPI scale to overlay size. dpi_scale: 2.0833333333333335. base_w: 2560.0. new_w: 1228.8,
6.382 D Dummy3 - Applying DPI scale to overlay size. dpi_scale: 2.0833333333333335. base_w: 2560.0. new_w: 1228.8,
6.384 D Dummy3 - Loading overlay.
11.449 D Dummy7 - Applying DPI scale to overlay size. dpi_scale: 2.0833333333333335. base_w: 2560.0. new_w: 1228.8,
11.460 D Dummy7 - Loading overlay.
26.084 D Dummy11 - Applying DPI scale to overlay size. dpi_scale: 2.0833333333333335. base_w: 2560.0. new_w: 1228.8,
26.118 D Dummy11 - Loading overlay.

> 

Now running mouseless with --dpi_scale 1 the correct Overlay size is displayed. The Overlay covers the whole screen. By tapping the shift key the Overlay switches to other displays and also covers the whole screen. 

> $ ./Mouseless_v0.4.0-preview.6.3d_ubuntu-24.04_x86_64.AppImage -d --dpi_scale 1
0.001 I Main - Starting mouseless v0.4.0-preview.6.3d (Linux - Ubuntu 24.04.2 LTS (x86_64))
0.112 I Main - Using dpi_scale from cli arg: 1.0
0.306 D Main - Initializing Overlay_1...
0.483 D Main - Initialization of Overlay_1 finished.
0.483 D Main - Initializing Overlay_2...
0.493 D Main - Initialization of Overlay_2 finished.
0.494 D Main - Initializing Overlay_3...
0.499 D Main - Initialization of Overlay_3 finished.
0.513 D Main - Checking for saved config...
0.524 D Main - Loaded saved config.
0.524 D Main - Applying config...
0.561 D Main - Config applied.
0.568 D Main - Initializing Main_Window...
0.598 D Main - Initialization of Main_Window finished.
0.599 D Main - Setting Main_Window content...
0.826 D Main - Content set for Main_Window.
0.846 D Main - Applying Main_Window style...
0.864 D Main - Main_Window style applied.
0.864 D Main - Activating module: 'welcome_tutorial'
0.865 D 1 (_check_for_updates_with_retries_inner) - Checking for updates...
0.865 I Main - Application is ready.
1.222 D 1 (_check_for_updates_with_retries_inner) - Current version 0.4.0-preview.6.3d is ahead of latest 0.4.0-preview.6.
1.365 D 2 - Applying DPI scale to overlay size. dpi_scale: 1.0. base_w: 2560.0. new_w: 2560.0,
1.367 D 2 - Applying DPI scale to overlay size. dpi_scale: 1.0. base_w: 2560.0. new_w: 2560.0,
1.369 D 2 - Applying DPI scale to overlay size. dpi_scale: 1.0. base_w: 2560.0. new_w: 2560.0,
13.119 D Dummy3 - Applying DPI scale to overlay size. dpi_scale: 1.0. base_w: 2560.0. new_w: 2560.0,
13.121 D Dummy3 - Loading overlay.

> 

BUT the mouse click is off. The cursor does not click in the right chosen position.
For instance: /// ist the position I've chosen (bottom right corner) but the mouse cursor appears in middle of the screen.
qqq and the cursor appears top left as it should.
nnq and the cursor appears in the left middle of the screen but should appear on bottom left screen. 
ttp and the cursor should appear top right of the screen but it appears top middle of the screen.

![Image](https://github.com/user-attachments/assets/e02da351-eb73-4635-9aab-1713f3e9d7ea)

Maybe you can also provide some diagnostics to determine where mouseless clicks  with -d option ( x,y coordinates).

**Comment by cymian** [comment]
Thank you for the update, @qrockz.

> Now running mouseless with --dpi_scale 1 the correct Overlay size is displayed

Interesting, I think your system ultimately doesn't need to 'account' for dpi_scale, at least when it comes to overlay size and position.

I suspect that using --dpi_scale 1 in the prior version would have made the overlay the right size as well.

Now let's see if I can figure out the mouse position on the next patch...

P.S. If you run with the `-p` flag, you should be able to see the output mouse coordinates.

**Comment by qrockz** [comment]
> I suspect that using --dpi_scale 1 in the prior version would have made the overlay the right size as well.

Yes, correct.

**Comment by 6e2f61** [comment]
Just confirming that with `--dpi-scale 1` overlay is full screen again, but mouse click is off :/

Here are my logs from running with `--dpi-scale 1 -d` flag.

```python
$ ./Mouseless_v0.4.0-preview.6.3d_arch-20250817.0.405639_x86_64.AppImage --dpi_scale 1 -d

0.003 I Main - Starting mouseless v0.4.0-preview.6.3d (Linux - Arch Linux (x86_64))
0.549 I Main - Using dpi_scale from cli arg: 1.0
1.249 E Main - No translation found for locale 'pl'. Falling back to 'en'.
1.460 D Main - Initializing Overlay_1...
1.938 D Main - Initialization of Overlay_1 finished.
1.938 D Main - Initializing Overlay_2...
1.981 D Main - Initialization of Overlay_2 finished.

==================================================
ALERT: Alert
==================================================
4.1 days remaining on your trial

Enjoy!  You can activate mouseless at any time from the status menu.
==================================================
Press Enter to continue...
4.971 D Main - Checking for saved config...
4.972 D Main - No saved config found, using default config.
4.972 D Main - Applying config...
5.001 D Main - Config applied.
5.026 D Main - Initializing Main_Window...
5.133 D Main - Initialization of Main_Window finished.
5.133 D Main - Setting Main_Window content...
5.682 D Main - Content set for Main_Window.
5.731 D Main - Applying Main_Window style...
5.793 D Main - Main_Window style applied.
5.794 D Main - Activating module: 'welcome_tutorial'
5.797 D 2 (_check_for_updates_with_retries_inner) - Checking for updates...
5.802 I Main - Application is ready.
6.207 D 2 (_check_for_updates_with_retries_inner) - Current version 0.4.0-preview.6.3d is ahead of latest 0.4.0-preview.6.
6.301 D 3 - Applying DPI scale to overlay size. dpi_scale: 1.0. base_w: 3840.0. new_w: 3840.0,
6.313 D 3 - Applying DPI scale to overlay size. dpi_scale: 1.0. base_w: 1920.0. new_w: 1920.0,
11.489 D Dummy4 - Applying DPI scale to overlay size. dpi_scale: 1.0. base_w: 1920.0. new_w: 1920.0,
11.499 D Dummy4 - Loading overlay.
12.610 D Dummy8 - Applying DPI scale to overlay size. dpi_scale: 1.0. base_w: 3840.0. new_w: 3840.0,
12.627 D Dummy8 - Loading overlay.
24.514 D Dummy18 - Deactivating module: 'welcome_tutorial'
24.514 D Dummy18 - Activating module: 'config_editor'
^CCleaning up WebView instances...
WebView cleanup completed gracefully.
``` 

And just from running with `-d` flag.

```python
$ ./Mouseless_v0.4.0-preview.6.3d_arch-20250817.0.405639_x86_64.AppImage -d
0.002 I Main - Starting mouseless v0.4.0-preview.6.3d (Linux - Arch Linux (x86_64))
0.459 D Main - Detected DPI: 120.0
0.964 E Main - No translation found for locale 'pl'. Falling back to 'en'.
1.099 D Main - Initializing Overlay_1...
1.406 D Main - Initialization of Overlay_1 finished.
1.406 D Main - Initializing Overlay_2...
1.432 D Main - Initialization of Overlay_2 finished.

==================================================
ALERT: Alert
==================================================
4.1 days remaining on your trial

Enjoy!  You can activate mouseless at any time from the status menu.
==================================================
Press Enter to continue...
16.988 D Main - Checking for saved config...
16.988 D Main - No saved config found, using default config.
16.988 D Main - Applying config...
17.007 D Main - Config applied.
17.026 D Main - Initializing Main_Window...
17.093 D Main - Initialization of Main_Window finished.
17.093 D Main - Setting Main_Window content...
17.450 D Main - Content set for Main_Window.
17.489 D Main - Applying Main_Window style...
17.533 D Main - Main_Window style applied.
17.533 D Main - Activating module: 'welcome_tutorial'
17.534 D 2 (_check_for_updates_with_retries_inner) - Checking for updates...
17.535 I Main - Application is ready.
17.907 D 2 (_check_for_updates_with_retries_inner) - Current version 0.4.0-preview.6.3d is ahead of latest 0.4.0-preview.6.
18.036 D 3 - Applying DPI scale to overlay size. dpi_scale: 1.25. base_w: 3840.0. new_w: 3072.0,
18.039 D 3 - Applying DPI scale to overlay size. dpi_scale: 1.25. base_w: 1920.0. new_w: 1536.0,
19.821 D Dummy4 - Applying DPI scale to overlay size. dpi_scale: 1.25. base_w: 1920.0. new_w: 1536.0,
19.828 D Dummy4 - Loading overlay.
20.302 D Dummy8 - Applying DPI scale to overlay size. dpi_scale: 1.25. base_w: 3840.0. new_w: 3072.0,
20.310 D Dummy8 - Loading overlay.
^CCleaning up WebView instances...
WebView cleanup completed gracefully.
```

I do not know if this is just logs, but when you run with `--dpi-scale 1` no indication that DPI is being read from `.Xresources` (detected). I says dpi set to 1, whereas when it detects DPI automatically sets it to 1.25

Fingers crossed you will trace this issue to the source :)

**Comment by cymian** [comment]
@qrockz @6e2f61 Are either of you able to quickly tell me if the mouse position is off both when a) clicking via subcell chars *and* b) pressing space to click where the virtual cursor is?  No worries if you're not able to check now -- should have a patch build shortly, just wanting to get things fully working for you on this one :)

Thank you both for the continued help figuring this out!

**Comment by cymian** [comment]
ok, new versions are up:

[Mouseless_v0.4.0-preview.6.4b_arch-20250817.0.405639_x86_64.AppImage](https://github.com/croian/mouseless/releases/download/v0.4.0-preview.6/Mouseless_v0.4.0-preview.6.4b_arch-20250817.0.405639_x86_64.AppImage)
[Mouseless_v0.4.0-preview.6.4b_arch-20250817.0.405639_x86_64.AppImage.sha256sum](https://github.com/croian/mouseless/releases/download/v0.4.0-preview.6/Mouseless_v0.4.0-preview.6.4b_arch-20250817.0.405639_x86_64.AppImage.sha256sum)
[Mouseless_v0.4.0-preview.6.4b_ubuntu-24.04_x86_64.AppImage](https://github.com/croian/mouseless/releases/download/v0.4.0-preview.6/Mouseless_v0.4.0-preview.6.4b_ubuntu-24.04_x86_64.AppImage)
[Mouseless_v0.4.0-preview.6.4b_ubuntu-24.04_x86_64.AppImage.sha256sum](https://github.com/croian/mouseless/releases/download/v0.4.0-preview.6/Mouseless_v0.4.0-preview.6.4b_ubuntu-24.04_x86_64.AppImage.sha256sum)

Notes:
- `--dpi_scale` is now `--dpi-scale` (hyphen instead of underscore)
  - you'll want to set dpi-scale to `1` as before
- at the bottom of the config editor, there's now a `Debug options` text field
  - paste the following into that field

```json
{ "mouse_screen_position_mult": 1, "mouse_screen_size_mult": 1 }
```

- adjust as needed, and press enter to validate
  - it's very basic, so if you accidentally write invalid json it will clear -- but you can 'restore saved' as usual
  - 2.083 for 200 dpi?

Please let me know how it goes, and what values ultimately work for you (hopefully some do!)

**Comment by qrockz** [comment]
> [@qrockz](https://github.com/qrockz) [@6e2f61](https://github.com/6e2f61) Are either of you able to quickly tell me if the mouse position is off both when a) clicking via subcell chars _and_ b) pressing space to click where the virtual cursor is? No worries if you're not able to check now -- should have a patch build shortly, just wanting to get things fully working for you on this one :)
> 
> Thank you both for the continued help figuring this out!

Free mode clicking works.
Subcell char clicking does not work. Mouse pointer shows up on a different place.

**Comment by qrockz** [comment]
> ok, new versions are up:
> 
> [Mouseless_v0.4.0-preview.6.4b_arch-20250817.0.405639_x86_64.AppImage](https://github.com/croian/mouseless/releases/download/v0.4.0-preview.6/Mouseless_v0.4.0-preview.6.4b_arch-20250817.0.405639_x86_64.AppImage) [Mouseless_v0.4.0-preview.6.4b_arch-20250817.0.405639_x86_64.AppImage.sha256sum](https://github.com/croian/mouseless/releases/download/v0.4.0-preview.6/Mouseless_v0.4.0-preview.6.4b_arch-20250817.0.405639_x86_64.AppImage.sha256sum) [Mouseless_v0.4.0-preview.6.4b_ubuntu-24.04_x86_64.AppImage](https://github.com/croian/mouseless/releases/download/v0.4.0-preview.6/Mouseless_v0.4.0-preview.6.4b_ubuntu-24.04_x86_64.AppImage) [Mouseless_v0.4.0-preview.6.4b_ubuntu-24.04_x86_64.AppImage.sha256sum](https://github.com/croian/mouseless/releases/download/v0.4.0-preview.6/Mouseless_v0.4.0-preview.6.4b_ubuntu-24.04_x86_64.AppImage.sha256sum)
> 
> Notes:
> 
>     * `--dpi_scale` is now `--dpi-scale` (hyphen instead of underscore)
>       
>       * you'll want to set dpi-scale to `1` as before
> 
>     * at the bottom of the config editor, there's now a `Debug options` text field
>       
>       * paste the following into that field
> 
> 
> { "mouse_screen_position_mult": 1, "mouse_screen_size_mult": 1 }
> 
>     * adjust as needed, and press enter to validate
>       
>       * it's very basic, so if you accidentally write invalid json it will clear -- but you can 'restore saved' as usual
>       * 2.083 for 200 dpi?
> 
> 
> Please let me know how it goes, and what values ultimately work for you (hopefully some do!)

Unfortunately the Overlay appears too small again with _--dpi-scale 1_
Also changing the _--dpi-scale_ value to different values does not effect the Overlay.

> $ ./Mouseless_v0.4.0-preview.6.4b_ubuntu-24.04_x86_64.AppImage -d --dpi-scale 3
> 0.132 I Main - Starting mouseless v0.4.0-preview.6.4b (Linux - Ubuntu 24.04.2 LTS (x86_64))
> 0.153 D Main - Detected DPI: 200.0
> 0.457 D Main - Initializing Overlay_1...
> 0.690 D Main - Initialization of Overlay_1 finished.
> 0.691 D Main - Initializing Overlay_2...
> 0.706 D Main - Initialization of Overlay_2 finished.
> 0.706 D Main - Initializing Overlay_3...
> 0.712 D Main - Initialization of Overlay_3 finished.
> 0.737 D Main - Checking for saved config...
> 0.749 D Main - Loaded saved config.
> 0.749 D Main - Applying config...
> 0.772 D Main - Config applied.
> 0.807 D Main - Initializing Main_Window...
> 0.848 D Main - Initialization of Main_Window finished.
> 0.848 D Main - Setting Main_Window content...
> 1.153 D Main - Content set for Main_Window.
> 1.185 D Main - Applying Main_Window style...
> 1.210 D Main - Main_Window style applied.
> 1.211 D Main - Activating module: 'welcome_tutorial'
> 1.212 D 1 (_check_for_updates_with_retries_inner) - Checking for updates...
> 1.212 I Main - Application is ready.
> 1.568 D 1 (_check_for_updates_with_retries_inner) - Current version 0.4.0-preview.6.4b is ahead of latest 0.4.0-preview.6.
> 2.259 D Dummy3 - Loading overlay.
> 3.075 D Dummy7 - Loading overlay.
> 3.617 D Dummy11 - Loading overlay.

![Image](https://github.com/user-attachments/assets/e40b979e-53db-4148-b307-5cb692f67ee2)

But free mode clicking works.

**Comment by 6e2f61** [comment]
Can't add anything extra. Exactly same behaviour for ma as for @qrockz with latest 6.4b_arch.
Changing `--dpi-scale` and `{ "mouse_screen_position_mult": 1, "mouse_screen_size_mult": 1 }` to any number has no effect. Overlay is too small, and clicks are now off always.

**Comment by cymian** [comment]
Sorry about that.  `--dpi-scale` should work again in this new version (I tested in an Ubuntu24 vm):

[Mouseless_v0.4.0-preview.6.4c_arch-20250817.0.405639_x86_64.AppImage](https://github.com/croian/mouseless/releases/download/v0.4.0-preview.6/Mouseless_v0.4.0-preview.6.4c_arch-20250817.0.405639_x86_64.AppImage)
[Mouseless_v0.4.0-preview.6.4c_arch-20250817.0.405639_x86_64.AppImage.sha256sum](https://github.com/croian/mouseless/releases/download/v0.4.0-preview.6/Mouseless_v0.4.0-preview.6.4c_arch-20250817.0.405639_x86_64.AppImage.sha256sum)
[Mouseless_v0.4.0-preview.6.4c_ubuntu-24.04_x86_64.AppImage](https://github.com/croian/mouseless/releases/download/v0.4.0-preview.6/Mouseless_v0.4.0-preview.6.4c_ubuntu-24.04_x86_64.AppImage)
[Mouseless_v0.4.0-preview.6.4c_ubuntu-24.04_x86_64.AppImage.sha256sum](https://github.com/croian/mouseless/releases/download/v0.4.0-preview.6/Mouseless_v0.4.0-preview.6.4c_ubuntu-24.04_x86_64.AppImage.sha256sum)

Edit:  If you have a multi-monitor setup, please check if you can get working debug options for all monitors!  The monitor at (0, 0) will likely not be affected by the `position_mult` value, but others will.

**Comment by 6e2f61** [comment]
Now for me with `--dpi-scale 1` and `{ "mouse_screen_position_mult": 1, "mouse_screen_size_mult": 1 }` overlay is in full screen 👌🏻 
Mouse clicks match overlay 👌🏻 

But mouse clicks always after second key press (never reached sub grid). Did I miss any option now? I didn't change any option. As of now all are default.

From UI perspective notification about Free Mode: On/Off jumps on the screen. Once left bottom corner, then with every key invocation is lower, lower and finally off the screen, then pops up in the center of the screen. 

Just FYI as this github issue (ticket?) is related to scaling, but there are some errors in console with non-standard keys on a keyboard. When I try to lower volume via multimedia key it causes errors in hotkey actions like (but volume change works though):

```python
Error in hotkey action: _handle_keyboard_event
Traceback (most recent call last):
  File "kb_tools/hid_event_bus.py", line 77, in _new_event_tap_callback
  File "kb_tools/keyboard/kb_input.py", line 492, in _handle_keyboard_event
  File "kb_tools/keyboard/kb_input.py", line 398, in _process_raw_event
  File "kb_tools/keyboard/keycode_maps.py", line 299, in get_web_key
KeyError: 'Favorites'
1637.770 E Dummy421 - Error in hotkey action: _handle_keyboard_event
1637.772 E Dummy421 - Traceback (most recent call last):
  File "kb_tools/hid_event_bus.py", line 77, in _new_event_tap_callback
  File "kb_tools/keyboard/kb_input.py", line 492, in _handle_keyboard_event
  File "kb_tools/keyboard/kb_input.py", line 398, in _process_raw_event
  File "kb_tools/keyboard/keycode_maps.py", line 299, in get_web_key
KeyError: 'Favorites'
```

**Comment by 6e2f61** [comment]
And finally mouseless crashed. Overlay stuck and keyboard was totally blocked. I left only with mouse clicks (they worked through overlay). But with i3 I was not able to do anything as keyboard is needed to every single thing in this WM. Had to hard reset PC to get operational again :D

I managed to take a screenshot of an error though

<img width="868" height="411" alt="Image" src="https://github.com/user-attachments/assets/c4d06ba2-2824-424b-8de0-9c938a08167a" />

**Comment by cymian** [comment]
@6e2f61 thank you for the updates!

> { "mouse_screen_position_mult": 1, "mouse_screen_size_mult": 1 } ... Mouse clicks match overlay 👌🏻

Interesting, I'm somewhat surprised by this result again 🤔  Good info to have -- should help me come up with an improved solution. 

> But mouse clicks always after second key press (never reached sub grid).

Check the `grid action level` setting (`subgrid` should be default).  There's a `cycle grid action level` command that changes it.

> From UI perspective notification about Free Mode: On/Off jumps on the screen. 

Will look into this!

> When I try to lower volume via multimedia key it causes errors in hotkey actions like...

Will fix!

> And finally mouseless crashed... Had to hard reset PC to get operational again :D

Oof, definitely want to fix this, and especially prevent the need to hard restart.  I think what happened is:

- Mouseless couldn't find any installed alert utility (it looks for zenity, kdialog, and xmessage in that order), so it fell back to using the console to print alerts
- While keyboard input was blocked, it was waiting for you to press enter in the terminal

I'll try to fix this (i.e. in this case, simply by not requiring user input to continue), but maybe the current workaround is to install zenity with pacman:

```sh
sudo pacman -S zenity
```

You could also maybe leave the a system/process monitor open so you can kill the Mouseless process with the mouse 😅

Also, if you have some other alert utility installed on your system, I'd be happy to know about it and try to integrate it.

---

Thanks again!  Cheers

**Comment by 6e2f61** [comment]
> Also, if you have some other alert utility installed on your system, I'd be happy to know about it and try to integrate it.

I had none until to now, to be honest I do not know if I missed any popup from anywhere, if so I'm just calmer because of that. I've installed `zenity`. Handy utility it helps when JS crashes which happened again today. Basically I can open settings only once. When I try to do after some time when app runs it is impossible 😅


> From UI perspective notification about Free Mode: On/Off jumps on the screen.

Also I'm changing screens via i3 (I have desktops 1-7 by default on display 1 and 8-0 on display 2). When I jump via i3 to desktop 8 (second screen) and enable *free mode* and try to scroll a page under mouse cursor, mouse goes back to desktop 1 (display 1) and shows up above free mode notification popup. Same happens when screens are changed via mosueless `Shift` key.

And another update regarding
> Check the grid action level setting (subgrid should be default). There's a cycle grid action level command that changes it.

It was set to value `2`. Somehow I've missed it scrolling through this single page of settings (*Maybe would be more user friendly to group opions into tabs someday as future enhancement*) I've changed in via UI to be `subgrid` saved and mouse clicks are again off the overlay. What's more I can't change setting back to value `2` (simply save button is grayed out).

Now to fix off overlay clicks I had to setup debug options to `{ "mouse_screen_position_mult": 1, "mouse_screen_size_mult": 1.25 }` to match clicks with overlay once more. My DPI value (120) is 125% of display native DPI, so this makes sense.

Now it works 👌🏻

**Comment by 6e2f61** [comment]
I found also configs are placed in `$HOME/.mouseless` rather than `$HOME/.config/mouseless`.
I know by default dotfiles are hidden, but I really do not like mess in my home directory ;-)

**Comment by cymian** [comment]
Thank you for the updates @6e2f61.

> Basically I can open settings only once. When I try to do after some time when app runs it is impossible 😅

> and enable free mode and try to scroll a page under mouse cursor, mouse goes back to desktop 1 (display 1)... Same happens when screens are changed via mosueless Shift key.

Will try to reproduce / fix!

---

> (Maybe would be more user friendly to group opions into tabs someday as future enhancement)

> I found also configs are placed in $HOME/.mouseless rather than $HOME/.config/mouseless.

Definitely plan on improving these soon :)

---

> I've changed in via UI to be subgrid saved and mouse clicks are again off the overlay.

I'm not clear on if this is still an issue or if it was fixed when you set `"mouse_screen_size_mult": 1.25`?

---

> What's more I can't change setting back to value 2 (simply save button is grayed out).

Interesting.  I've reproduced this one -- will investigate and try to fix.  You should be able to change any other setting then save, then revert the other setting and save again 😅

**Comment by qrockz** [comment]
`$ ./Mouseless_v0.4.0-preview.6.4c_ubuntu-24.04_x86_64.AppImage --dpi-scale 1`
`{ "mouse_screen_position_mult": 1, "mouse_screen_size_mult": 2.08333 }`

These settings work for me to get accurate clicks and fullsize Overlay.
